name: Coveralls

on:
  push:
    branches: [ main ]
    tags:
      - v*.*.*
      - test*
    paths:
      - '!README.md'
      - '!CONTRIBUTING.md'
      - '!docs/**'
      - 'include/**'
      - 'demo/**'
      - '.github/**'
      - 'tests/**'

  pull_request:
    branches: [ main ]
    paths:
      - '!README.md'
      - '!CONTRIBUTING.md'
      - '!docs/**'
      - 'include/**'
      - 'demo/**'
      - '.github/**'
      - 'tests/**'

env:
  BUILD_TYPE: Debug
  TOKEN: ${{secrets.COVERITY_TOKEN}}

jobs:
  Windows:
    runs-on: windows-2022

    defaults:
      run:
        shell: powershell

    steps:
    - uses: actions/checkout@v2

    - uses: ilammy/msvc-dev-cmd@v1
      with:
        arch: x64

    - name: Setup Dependencies
      shell: powershell
      run: |
        choco install -y 7zip.install
        curl.exe -OL https://github.com/niXman/mingw-builds-binaries/releases/download/13.2.0-rt_v11-rev0/x86_64-13.2.0-release-win32-seh-msvcrt-rt_v11-rev0.7z
        7z x x86_64-13.2.0-release-win32-seh-msvcrt-rt_v11-rev0.7z

    - name: Configure CMake
      run: cmake -B build_test -G "MinGW Makefiles" tests
      env:
        CC: ${{github.workspace}}/mingw64/bin/gcc.exe
        CXX: ${{github.workspace}}/mingw64/bin/g++.exe

    - name: Build
      run: cmake --build build_test --config ${{env.BUILD_TYPE}}

    - name: Test
      run: ctest -C ${{env.BUILD_TYPE}} --test-dir build_test --output-on-failure

    - name: Submit results to Coveralls using cpp-coveralls
      run: |
        pip install cpp-coveralls
        coveralls -r ./ -E ".*/tests/.*" -E ".*/build_test/.*" -E ".*/demo/.*" t ${{env.TOKEN}}
