name: Coveralls

on:
  push:
    branches: [ main ]
    tags:
      - v*.*.*
      - test*
    paths:
      - '!README.md'
      - '!CONTRIBUTING.md'
      - '!docs/**'
      - 'include/**'
      - 'demo/**'
      - '.github/**'
      - 'tests/**'

  pull_request:
    branches: [ main ]
    paths:
      - '!README.md'
      - '!CONTRIBUTING.md'
      - '!docs/**'
      - 'include/**'
      - 'demo/**'
      - '.github/**'
      - 'tests/**'

env:
  BUILD_TYPE: Debug
  TOKEN: ${{secrets.COVERITY_TOKEN}}

jobs:
  Windows:
    runs-on: windows-2022

    defaults:
      run:
        shell: powershell

    steps:
    - uses: actions/checkout@v2

    - uses: ilammy/msvc-dev-cmd@v1
      with:
        arch: x64

    - name: Install cpp-coveralls
      run: pip install --user cpp-coveralls

    - name: Configure CMake
      run: cmake -B build_test -G "MinGW Makefiles" tests

    - name: Build
      run: cmake --build build_test --config ${{env.BUILD_TYPE}}

    - name: Test
      run: ctest -C ${{env.BUILD_TYPE}} --test-dir build_test --output-on-failure

    - name: Collect gcov files
      run: |
        cmake -B build_test tests -DCOVERAGE=1
        tar xvf build_test/gcov.tar.gz

    - name: Submit the gcov into the Coveralls
      run: coveralls -i Testing/CoverageInfo/fluent_tray.hpp.gcov -t ${{env.TOKEN}}
