name: Windows

on:
  push:
    branches: [ main ]
    tags:
      - v*.*.*
    paths:
      - '!README.md'
      - '!CONTRIBUTING.md'
      - '!docs/**'
      - 'include/**'
      - 'demo/**'
      - '.github/**'
      - 'tests/**'

  pull_request:
    branches: [ main ]
    paths:
      - '!README.md'
      - '!CONTRIBUTING.md'
      - '!docs/**'
      - 'include/**'
      - 'demo/**'
      - '.github/**'
      - 'tests/**'

env:
  BUILD_TYPE: Debug

jobs:
  x64:
    runs-on: windows-2022

    steps:
    - uses: actions/checkout@v2
    - uses: ilammy/msvc-dev-cmd@v1
      with:
        arch: x64

    - name: Configure CMake
      run: |
        cmake -B ${{github.workspace}}/build_msvc_x64 -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}} -A x64 demo

    - name: Build
      run: |
        cmake --build ${{github.workspace}}/build_msvc_x64 --config ${{env.BUILD_TYPE}}

  x86:
    runs-on: windows-2022

    steps:
    - uses: actions/checkout@v2
    - uses: ilammy/msvc-dev-cmd@v1
      with:
        arch: x86

    - name: Configure CMake
      run: |
        cmake -B ${{github.workspace}}/build_msvc_x86 -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}} -A Win32 -DBIT_TYPE=32 demo

    - name: Build
      run: |
        cmake --build ${{github.workspace}}/build_msvc_x86 --config ${{env.BUILD_TYPE}}
